### ISSUE TITLE
问个问题，shashlik 编译

### ISSUE THREAD

**Issue by cgoxopx** [chainsx/centos64-rpi#1]
shashlik 怎么在RPI上编译？或者是用anbox也行

**Comment by chainsx** [comment]
运行安卓应用。。。。。
我早就试过了。。只支持`amd64`。。。所以没办法，你自己看，shashlik其实就是内置了一个安卓的镜像。。。
所以现在最好的办法是用`chromium`运行（动态加载）apk，具体方法百度上有。
不过，还是有一个问题，就是gpu的问题，
在chromium里输入`chrome://gpu`查看gpu情况，要`Native GpuMemoryBuffers`和`WebGL`两项显示通过才能加载apk，，，，但是树莓派系统是通不过的。。。。。
所以又要编译内核添加支持。。。。
所以很复杂。
我折腾了很久才勉强能运行apk。
不过推荐一个基于chromiumOS改的系统，叫flintOS，
支持rpi，gpu也没问题，，就是没法拓展根目录。。。
如果你有多余的sd卡可以试试。

**Comment by cgoxopx** [comment]
扩展根目录用gparted？

**Comment by chainsx** [comment]
不行，chromiumOS分区复杂，而且根目录不在最后一个分区。
